### ISSUE TITLE
Add docs for releasing cli for users

### ISSUE THREAD

**Issue by pushpak1300** [DannyBen/bashly#104]
A document or how-to guide would be very helpful to show how the generated cli can be released.
eg. https://oclif.io/docs/releasing

**Comment by DannyBen** [comment]
Releasing / publishing a bash script (or any other app) can be done in many ways, depending on your expertise, your audience, and the level of effort you care to invest.

Since bashly generates a standalone shell script, it is as simple as downloading it and placing it in the path.

The [Examples](https://bashly.dannyb.co/examples/) section in the documentation points to a few Real World examples of mine, in which I use provide a setup script for users and a one-line command they can run to run this setup, for example:

```bash
$ bash <(curl -Ls get.dannyb.co/rush/setup)
# which is basically the same as
$ bash <(curl -Ls https://raw.githubusercontent.com/DannyBen/rush-cli/master/setup)
```

The installation instructions and setup scripts can be viewed [here](https://github.com/DannyBen/rush-cli#installation), [here](https://github.com/DannyBen/opcode#install), and [here](https://github.com/DannyBen/alf#installation).

In any case, I do not consider myself an expert in the different ways you can use to publish your apps, and I am not sure this type of information falls within the scope of the bashly documentation.
