### ISSUE TITLE
exit/return behavior of wrapped scripts

### ISSUE THREAD

**Issue by natling** [DannyBen/bashly#315]
should a script generated with `--wrap FUNCTION` call `return` where a non-wrapped script would `exit`? when i source a wrapped script and call the resulting function from an interactive shell and not another script, if one of its internal `*parse_requirements` functions exits because of invalid input (or `--help` or `--version`), it prints the error (or calls the relevant `*usage` or `version_command`) and then exits the shell instead of returning control to it.

**Comment by DannyBen** [comment]
You are probably right. I am wondering if the `--wrap` function is needed at all. I am not sure I get its use case.

**Comment by DannyBen** [comment]
Thinking about it more, it seems like this would be a complex change.
Simply changing the word `exit` with the word `return` will not create a valid script, since the exit behavior is assumed to exist throughout the script. When an internal function calls another internal function, it assumes it will exit on failure, and therefore there are no checks for such return values.

This puts `--wrap` even deeper on the chopping block.

**Comment by DannyBen** [comment]
At this point in time I am leaning towards closing this ticket, due to these points:

1. Bashly is designed to generate scripts, not sourcable functions.
2. The `--wrap` feature is designed to allow sourcing the result in another script, and I consider it the non-common edge case for most users.
3. Any change of `exit` to `return` in the bashly generated source has a chance of surfacing new subtle errors.
4. The `set -e` that normally exists in the `initialize` function does not play well with `return 1`.

I will keep this issue open for a few more days, if anyone wants to chime in with practical solutions to any of these points.

**Comment by natling** [comment]
all good and reasonable points. i hope there is a future for `--wrap` but i understand that its usage is an edge case. i have spent a lot of time recently thinking about the subtleties of `exit`, `return`, `source`, `trap` and many other relevant shell topics – there is certainly no shortage of complexity here. if i come up with solutions i will bring them up but in the meantime im not opposed to closing the issue. thank you for all your work on bashly! it is a real joy to use.

**Comment by DannyBen** [comment]
Thank you! 
The `--wrap` functionality is not going away, and perhaps there could be a not so complicated way to make it support this use case. I might take a deeper look at it.

I think one problem that made me stop investigating, is that `set -e` in conjunction with `return 1`, that is a replacement for `exit 1`.

I guess one way to start testing how this change might be able to work, is to take the plain script generated by `bashly g` or even `bashly g --minimal`, and modify it manually to support the tty sourcing. Then, if this works, it will be easy to port these changes back to the templates.

**Comment by DannyBen** [comment]
How about this solution:

**Step 1: Change all `exit 1` to `return 1`.**
This change already works as is, thanks to the presence of `set -e` in the `initialize()` function.

**Step 2: Change all successful `exit` to the following**

```bash
wants_to_exit=true
return 0
```

**Step 3: Change all calls to functions that may want to exit to the following**

```bash
parse_requirements "$@"
[[ $wants_to_exit == true ]] && return 0
```

Here is a full minimal script:

```bash
#!/usr/bin/env bash 

parse_requirements() {
  echo "parsing requirements"
  # if something that needs to exit with success happens
  if [[ "$1" == "--version" ]]; then
    wants_to_exit=true
    return 0
  fi
}

initialize() {
  # we already have set -e in bashly's initialize function
  set -e
}

run() {
  parse_requirements "$@"
  [[ $wants_to_exit == true ]] && return 0
  echo "Continuing execution here"
}

run "$@"
```

From what I have seen, the `exit` statements are mostly (only?) in the `parse_requirements` functions, so things are relatively contained.

This will mean there will be 0 `exit` statements in any bashly generated code, so it should work as a function as well.

I wonder if:

1. Does this seem like a good solution?
2. Is there a more elegant way of achieving the same?

**Comment by DannyBen** [comment]
I am closing this as I am unable to come up with a stable solution.
I am open to discussing again if there will be more demand, or a proposal for a reliable solution.
