### ISSUE TITLE
Is there any security consideration for the "bash name"?

### ISSUE THREAD

**Issue by MIngPAPA** [DannyBen/bashly#350]
Currently, the "name" of the bash command line is limited to the following lines in `config_validator.rb`
```
 assert value['name'].match(/^[a-z0-9_-]+$/),
        "#{key}.name must only contain lowercase alphanumeric characters, hyphens and underscores"
```
What if `assert value['name'].match(/^[a-z0-9\._-]+$/),`, i.e. use a "dot" in the bash command?
> #{key}.name must only contain lowercase alphanumeric characters, hyphens , dot and underscores

Will it cause any disaster?

Thanks

**Comment by MIngPAPA** [comment]
Thanks for your warm reply！
Yes, currently I have a situation. For example, a traditional bash script `hello.sh` with quite a lot of subcommands causing system complexity. As a result, I separate it into different modules, such as `hello-nice.sh`, `hello-bye.sh`, `hello-world.sh` etc. 
The '-' & '_' is well applied.
 `hello.nice.sh`, `hello.bye.sh`, `hello.world.sh`, or even `hello.nice`, `hello.bye`, `hello.world` will it be a *good* implement or not, in your opinion?

**Comment by DannyBen** [comment]
Well,

The fact that command.name did not allow for dot, was definitely an oversight. I fixed that.
If you wish to use it right away, you can use the [edge version](https://github.com/DannyBen/bashly/tree/master/edge#testing-unreleased-edge-bashly-versions) - let me know if you need help with that.

As for creating multiple script due to complexity - sure, it is an option.

Just to give you a few more options to consider - not sure if any of these will help you, but you should be aware they exist to help with complex scripts.

1. There is the option to separate the bashly config file into several files. More info in the [Advanced Features > Split Config](https://bashly.dannyb.co/advanced/split-config/) section of the docs.
2. There is an option to create extensible scripts. Sort of like `git` does: If you place an executable file named `git-anything` in your path, then running `git anything` will execute it. More on this in the [Advanced Features > Extensible Scripts](https://bashly.dannyb.co/advanced/extensible-scripts/) section of the docs.

As always, let me know if you need further help.
