### ISSUE TITLE
Launch error on Ubuntu WSL 22.04 after fresh installation [SOLVED]

### ISSUE THREAD

**Issue by carlospalavecino** [DannyBen/bashly#410]
### URL

https://bashly.dannyb.co/installation/

### Description

Hi, I discovered bashly today and wanted to give it a try. Note that I've never used Ruby before. 
I followed the installation guide as the documentation says.

>[!NOTE] 
> Im on WSL Ubuntu so i install ruby-rubygems ( this could be included as dependencies for newbies)
```bash
➜  ~ sudo apt install -y ruby-rubygems
➜  ~ gem -v
3.3.5
➜  ~ ruby -v             
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```
I install bashly
```bash
gem install bashly
```
I got permission errors,  so i try
```bash
gem install --user-install bashly
```
> [!NOTE]  
> sudo resolves the problem, maybe it could be documented the global and de local installation

The installation finished without any problems

But when i try to run bashly i got this error
```bash
/home/user/.local/share/gem/ruby/3.0.0/gems/bashly-1.0.7/lib/bashly/extensions/yaml.rb:6:in `singleton class': undefined method `unsafe_load' for class `#<Class:Psych>' (NameError)
        from /home/user/.local/share/gem/ruby/3.0.0/gems/bashly-1.0.7/lib/bashly/extensions/yaml.rb:5:in `<module:YAML>'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/bashly-1.0.7/lib/bashly/extensions/yaml.rb:1:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/requires-1.0.1/lib/requires.rb:8:in `block in requires'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/requires-1.0.1/lib/requires.rb:7:in `each'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/requires-1.0.1/lib/requires.rb:7:in `requires'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/bashly-1.0.7/lib/bashly.rb:9:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/user/.local/share/gem/ruby/3.0.0/gems/bashly-1.0.7/bin/bashly:2:in `<top (required)>'
        from /home/user/.local/share/gem/ruby/3.0.0/bin/bashly:25:in `load'
        from /home/user/.local/share/gem/ruby/3.0.0/bin/bashly:25:in `<main>'
```

> [!IMPORTANT]  
> Updating psych resolves the error but i got a dependency error too, so i resolve the dependency installing libyaml-dev
>```bash
>  sudo apt install -y libyaml-dev \
>  sudo gem update psych
> ```
 Updating psych on a default ubuntu installation (WSL) resolves the issue. For a newbie like me it was difficult to find the solution, it took me a few hours, maybe it would be a good idea to add this hint in the documentation.

Greetings

**Comment by DannyBen** [comment]
Thanks for this, and I am glad you made it work.

Installing Ruby properly, with all its system dependencies, can be done in more than one way, and has different dependency names in each operating system. It is outside the scope of Bashly's documentation.

The issues you encountered here are not bashly-specific.

**Comment by carlospalavecino** [comment]
I understand, but in that case, It would be limiting the use only to people who use or handle ruby. I mean that to have the application running is not enough to have ruby-gem installed. 

I don't know if it would apply in other environments (haven't tested it yet) but I need libyaml-dev and psych updated to bashly run properly (Its not a default installation). I'm definitely not an expert developer, but i know some stuff for a while and it took me a lot of time and several searches and try a few solutions to realize that it was a dependency error.
 
Perhaps it would be enough to just mention the minimum version of psych supported and clarify that there is a dependency on libyaml-dev  as a requirement. Keep in mind that Bashly is really great and there are newbie users (like me) who might not complete the installation, and that its a shame.

I was playing arround all the day and let me thank you for all your work, it's really amazing

**Comment by DannyBen** [comment]
I share your frustration. Installing Ruby should have been much easier than it is.

Installing ruby properly (i.e. so that you can install gems with native extensions) requires several OS packages (not only libyaml). The error you faced with Psych (the YAML parser gem) is very weird. The missing method mentioned - `unsafe_load` - is [in Psych for 2 years, and 2 major versions ago](https://github.com/ruby/psych/commit/cb50aa8d3fb8be01897becff77b4922b12a0ab4c).

What is weird about it, is that Ruby 3.0 (which is the oldest supported Ruby), [comes with Psych 4.0](https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias/71192990#71192990), which should already have the `unsafe_load` method.

So - if Ruby 3.x is properly installed, there should be no problem. The apt version of Ruby is not the recommended Ruby to install. Usually it is best to install it with a Ruby version manager, like rbenv.

Personally - [this is how I install Ruby](https://github.com/DannyBen/rush-repo/blob/master/ruby/main).

> Perhaps it would be enough to just mention the minimum version of psych

- Gem dependencies should not be mentioned in documentation, but in the gem's manifest (gemspec).
- Psych is a "core gem" - and should normally not be version-limited in the gemspec.
- Bashly [specifies](https://github.com/DannyBen/bashly/blob/f8995c6c0fa4b41cac8b428ed70ebf01fcc6a6d2/bashly.gemspec#L16) that it needs Ruby 3.0 or higher, which normally comes with an up to date Psych - I will check if there is a case that it doesn't.

> clarify that there is a dependency on libyaml-dev as a requirement

This is not the only Ruby OS dependency. It is the only one you were missing.

**Comment by DannyBen** [comment]
I see that the apt Ruby 3.0 comes with Psych 3.3.0, which is just shy of 3.3.2, which is the first version that supportes the `unsafe_load`

I will see if I can do an Installation Troubpleshooting page or something like this, because it is really easy to solve if you deal with Ruby a lot, and probably frustrating if you are not.

**Comment by DannyBen** [comment]
Ok - here is my attempt at alleviating the Ruby installation frustration:

1. I have added an [Installing Ruby](https://bashly.dannyb.co/installing-ruby/) page to the documentation (linked from the [Installation](https://bashly.dannyb.co/installation/) page).
2. I have added a Psych version requirement to the gemspec:
    https://github.com/DannyBen/bashly/blob/acfc6b8681938070968172d9d1144c9faf0f7261/bashly.gemspec#L26-L28

Is this satisfactory?
