### ISSUE TITLE
Blank lines, comments and order are not retained when modifying configuration files

### ISSUE THREAD

**Issue by chovanecadam** [DannyBen/bashly#416]
### Bashly Version

Latest Ruby Gem

### Description

Hello. Configuration files often contain comments with links to documentation, default values or other stuff. Order and blank lines of the items help users to navigate in long configuration files. The current implementation removes blank lines and comments and reorders elements. I would prefer if this was not the case. This should be noted in the docs, as it could surprise some people.

This change would require to rewrite the current implementation of config.sh library functions (an ini.sh as well probably). I could contribute if you were interested in this change (parsing the configuration file line-by-line instead of loading it into an array).

Anyway, I am very grateful for this tool, you are doing a tremendous job! :+1: 

### Reproduction Steps

1. Create some configuration file with comments and blank lines, notice the ordering of the elements
2. Call `config_set key value` somewhere in the script
3. Notice that blank lines, comments and order are not retained

**Comment by DannyBen** [comment]
Thanks for taking the time to write this proposal, and I am happy you find bashly useful.

This approach to INI file processing is by design. As you noted, having it preserve the non key-value lines in the file will most likely require a more complex implementation. Since I am the (mostly-) sole maintainer of multiple open source repositories and Ruby gems, I favor simplicity above all else.

That said:

1. All the library features in Bashly are designed as a starting point. They are intentionally injected to "userland" so that the you can change them as you see fit.
2. In case you are developing more than one script with Bashly, and wish to have your own repository of libraries that can be added with `bashly add`, you can have a [custom library source](https://bashly.dannyb.co/advanced/lib-source/).
3. If you happen to create a config library that is able to preserve order, comments and empty lines **while still keeping it simple and readable, and without breaking its current API** - I am willing to consider replacing the existing library. 

I hope this makes sense, and as always - I am open to further discussion and to be convinced otherwise.
