### ISSUE TITLE
Is there an "official" way to call a command from within a command?

### ISSUE THREAD

**Issue by abh1kg** [DannyBen/bashly#72]
I know I can probably do this by invoking the generated function but I am looking for some documentation-based guidance (if possible) on this scenario. I have two commands, let's say, `cli dothis` and `cli dothat`.
I want to call `cli dothat` from within the implementation for `cli dothis`. Can this be done without knowing the internals of the generated bashly file?

**Comment by DannyBen** [comment]
Well, I don't know about "official way" but I can recommend that you simply avoid this problem.

Instead of calling one command from another command, do a bash function (inside the `lib` directory) that will be called by both commands.

You can see for example the `lib` folder in [rush](https://github.com/DannyBen/rush-cli/tree/master/src/lib) or in [alf](https://github.com/DannyBen/alf/tree/master/src/lib).

In any case, I would not recommend calling the functions generated by bashly, as these are not guaranteed to stay the same.
